AWSTemplateFormatVersion: "2010-09-09"

Description: Amazon Transcribe Live Call Analytics - LCA SSM Parameters

Parameters:
  # Required
  LCAStackName:
    Type: String
    Description: LCA Stack Name

  LLMPromptSummaryTemplate:
    Type: String
    Description: >-
      Prompt to use to generate insights for a call. This can be a single string where an LLM returns a string,
      or a single string where the LLM returns a JSON object with key/value pairs, or a string that contains
      a JSON Object with key/value pairs, where the LLM will run one inference on each key/value pair with the value
      containing the prompt. Use {transcript} as a placeholder for where the call transcript will be injected.
    Default: >-
      {
        "Summary":"The following is the transcript of a call.<br><transcript><br>{transcript}<br></transcript><br><br>Write a concise summary of the call without preamble or additional explanation. Where possible reference speaker names, but only use gender neutral pronouns.",
      "Topic":"The following is the transcript of a call.<br><transcript><br>{transcript}<br></transcript><br><br>What is the topic of the call? For example, iphone issue, billing issue, cancellation. Only reply with the topic, nothing more.",
        "Follow-Up Actions":"The following is the transcript of a call.<br><transcript><br>{transcript}<br></transcript><br><br>Based on the transcript given above extract a list of actionable items in the following Markdown format: <br><br>**1.[Concise description of the action item without any names**]<br><br>[Longer description of the action item without any names]<br><br>**Owner:** [The person or role responsible for the action if it can be determined, or ’TBD’]<br><br>**Due Date:** [The date the action item should be completed by if it can be determined, or ’TBD’]<br><br><br>**2. [Concise description of the next action item without any names]**<br><br>Longer description of the next action item without any names]<br><br>**Owner:** [The person or role responsible for the next action if it can be determined, or ’TBD’]<br><br>**Due Date:** [The due date for the next action if it can be determined, or ’TBD’]<br><br><br><br>Please present, the action items in a clean, organized, and easy-to-read Markdown format without preamble or additional explanation."
      }

Resources:
  LLMPromptSummaryTemplateParameter:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: !Sub "${LCAStackName}-LLMPromptSummaryTemplate"
      Type: String
      Description: >
        Prompt to use to generate insights for a call. This can be a single string where an LLM returns a string,
        or a single string where the LLM returns a JSON object with key/value pairs, or a string that contains
        a JSON Object with key/value pairs, where the LLM will run one inference on each key/value pair with the value
        containing the prompt. Use {transcript} as a placeholder for where the call transcript will be injected.
      Value: !Ref LLMPromptSummaryTemplate

Outputs:
  LLMPromptSummaryTemplateParameter:
    Value: !Ref LLMPromptSummaryTemplateParameter
